# Generated by Django 2.0.6 on 2018-06-09 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('userLock', models.IntegerField(default=0)),
                ('userFreeze', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('userGroupId', models.AutoField(primary_key=True, serialize=False)),
                ('userGroupName', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userInfoId', models.AutoField(primary_key=True, serialize=False)),
                ('userPhone', models.BigIntegerField(null=True)),
                ('userSex', models.CharField(max_length=6, null=True)),
                ('userQq', models.IntegerField(null=True)),
                ('userEmail', models.EmailField(max_length=254, null=True)),
                ('userAddress', models.TextField(null=True)),
                ('userMark', models.IntegerField(default=0)),
                ('userRank', models.IntegerField(default=0)),
                ('userLastIp', models.GenericIPAddressField(null=True)),
                ('userBirthday', models.IntegerField(null=True)),
                ('userDescription', models.TextField(null=True)),
                ('userImageUrl', models.ImageField(null=True, upload_to='')),
                ('userSchool', models.TextField(null=True)),
                ('userRegisterTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('userRegisterIp', models.GenericIPAddressField(null=True)),
                ('userWeiBo', models.URLField(null=True)),
                ('userBloodType', models.CharField(max_length=6, null=True)),
                ('userSay', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserMark',
            fields=[
                ('userMarkId', models.AutoField(primary_key=True, serialize=False)),
                ('userMarkNumber', models.IntegerField(default=0)),
                ('userMarkName', models.CharField(default='小白', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserGroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='userRank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserMark'),
        ),
    ]
