# Generated by Django 2.0.6 on 2018-07-09 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleId', models.AutoField(primary_key=True, serialize=False)),
                ('articleName', models.CharField(max_length=128, null=True)),
                ('articleTime', models.DateTimeField(auto_now=True)),
                ('articleIp', models.GenericIPAddressField(null=True)),
                ('articleClick', models.IntegerField(default=0)),
                ('articleContent', models.TextField()),
                ('articlePower', models.IntegerField(default=1)),
                ('articleTop', models.IntegerField(default=0)),
                ('articleSuperTop', models.IntegerField(default=0)),
                ('articleComment', models.IntegerField(default=0)),
                ('articleLike', models.IntegerField(default=0)),
                ('articleUrl', models.URLField(null=True, unique=True)),
                ('status', models.IntegerField(null=True)),
                ('saveType', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleBlogCategory',
            fields=[
                ('articleBlogCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('articleBlogCategoryName', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleBlogCategoryTwo',
            fields=[
                ('articleBlogCategoryTwoId', models.AutoField(primary_key=True, serialize=False)),
                ('articleBlogCategoryTwoName', models.CharField(max_length=60, null=True)),
                ('ArticleBlogCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleBlogCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('articleCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('articleCategoryName', models.TextField(null=True)),
                ('articleTemplate', models.TextField(null=True)),
                ('articleUuid', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-articleCategoryId'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('articleTagId', models.AutoField(primary_key=True, serialize=False)),
                ('articleId', models.TextField(null=True)),
                ('articleTagName', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('commentContent', models.TextField()),
                ('commentTime', models.DateTimeField(auto_now_add=True)),
                ('commentIp', models.GenericIPAddressField()),
                ('commentUUID', models.CharField(max_length=100, null=True, unique=True)),
                ('commentArticle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article', to_field='articleUrl')),
            ],
            options={
                'ordering': ['-commentId'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('secretID', models.AutoField(primary_key=True, serialize=False)),
                ('sendId', models.IntegerField(null=True)),
                ('receiveId', models.IntegerField(null=True)),
                ('messageTitle', models.CharField(max_length=64, null=True)),
                ('messageContent', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('systemMsgId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('userLock', models.IntegerField(default=0)),
                ('userFreeze', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAttention',
            fields=[
                ('userAttentionId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField(null=True)),
                ('attentionUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('userGroupId', models.AutoField(primary_key=True, serialize=False)),
                ('userGroupName', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userInfoId', models.AutoField(primary_key=True, serialize=False)),
                ('userPhone', models.BigIntegerField(null=True)),
                ('userSex', models.CharField(max_length=6, null=True)),
                ('userQq', models.IntegerField(null=True)),
                ('userEmail', models.EmailField(max_length=254, null=True)),
                ('userAddress', models.TextField(null=True)),
                ('userMark', models.IntegerField(default=0)),
                ('userRank', models.IntegerField(default=0)),
                ('userLastIp', models.GenericIPAddressField(null=True)),
                ('userBirthday', models.IntegerField(null=True)),
                ('userDescription', models.TextField(null=True)),
                ('userImageUrl', models.ImageField(null=True, upload_to='')),
                ('userSchool', models.TextField(null=True)),
                ('userRegisterTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('userRegisterIp', models.GenericIPAddressField(null=True)),
                ('userWeiBo', models.URLField(null=True)),
                ('userBloodType', models.CharField(max_length=6, null=True)),
                ('userSay', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserMark',
            fields=[
                ('userMarkId', models.AutoField(primary_key=True, serialize=False)),
                ('userMarkNumber', models.IntegerField(default=0)),
                ('userMarkName', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userGroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.UserGroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='userRank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.UserMark'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parentsComment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Comment', to_field='commentUUID'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='ArticleBlogCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleBlogCategory'),
        ),
        migrations.AddField(
            model_name='article',
            name='ArticleBlogCategoryTwo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleBlogCategoryTwo'),
        ),
        migrations.AddField(
            model_name='article',
            name='articleCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleCategory'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
    ]
