# Generated by Django 2.0.6 on 2018-06-12 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180611_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleId', models.AutoField(primary_key=True, serialize=False)),
                ('articleName', models.CharField(max_length=128)),
                ('articleTime', models.DateTimeField(auto_now=True)),
                ('articleIp', models.GenericIPAddressField(null=True)),
                ('articleClick', models.IntegerField(default=0)),
                ('articleContent', models.TextField()),
                ('articlePower', models.IntegerField(default=1)),
                ('articleTop', models.IntegerField(default=1)),
                ('articleSuperTop', models.IntegerField(default=0)),
                ('articleComment', models.IntegerField(default=0)),
                ('articleLike', models.IntegerField(default=0)),
                ('articleUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('articleCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('articleCategoryName', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('commentContent', models.TextField()),
                ('commentTime', models.DateTimeField(auto_now_add=True)),
                ('commentIp', models.GenericIPAddressField()),
                ('commentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('secretID', models.AutoField(primary_key=True, serialize=False)),
                ('sendId', models.IntegerField(null=True)),
                ('receiveId', models.IntegerField(null=True)),
                ('messageTitle', models.CharField(max_length=64, null=True)),
                ('messageContent', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('systemMsgId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAttention',
            fields=[
                ('userAttentionId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField(null=True)),
                ('attentionUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='articleCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleCategory'),
        ),
    ]
