# Generated by Django 2.0.6 on 2018-07-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180709_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userComment',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userFans',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userView',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userlike',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
