# Generated by Django 2.0.6 on 2018-06-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articlecategory_articleuuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
