# Generated by Django 2.0.6 on 2018-07-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180711_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userAriticle',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
