# Generated by Django 2.0.6 on 2018-06-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180612_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='articleTemplate',
            field=models.TextField(null=True),
        ),
    ]
