# Generated by Django 2.0.6 on 2018-07-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userinfo_userariticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='userAriticle',
            new_name='userArticle',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='userlike',
            new_name='userLike',
        ),
    ]
