# Generated by Django 2.0.6 on 2018-06-13 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_articlecategory_articletemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBlogCategory',
            fields=[
                ('articleBlogCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('articleBlogCategoryName', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
        migrations.AlterField(
            model_name='article',
            name='articleCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleCategory'),
        ),
        migrations.AddField(
            model_name='article',
            name='ArticleBlogCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleBlogCategory'),
        ),
    ]
