# Generated by Django 2.0.6 on 2018-06-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_articlecategory_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleblogcategorytwo',
            old_name='articleBlogCategoryId',
            new_name='articleBlogCategoryTwoId',
        ),
        migrations.RenameField(
            model_name='articleblogcategorytwo',
            old_name='articleBlogCategoryTwo',
            new_name='articleBlogCategoryTwoName',
        ),
        migrations.AddField(
            model_name='article',
            name='ArticleBlogCategoryTwo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleBlogCategoryTwo'),
        ),
    ]
