# Generated by Django 2.0.6 on 2018-06-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180619_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentArticle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
        migrations.AddField(
            model_name='comment',
            name='fatherComment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
        migrations.AlterField(
            model_name='article',
            name='articleTop',
            field=models.IntegerField(default=0),
        ),
    ]
