# Generated by Django 2.0.6 on 2018-07-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180711_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userNickName',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
