# Generated by Django 2.0.6 on 2018-06-21 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180621_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleUrl',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentArticle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article', to_field='articleUrl'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='fatherComment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
    ]
