# Generated by Django 2.0.6 on 2018-06-14 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180614_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBlogCategoryTwo',
            fields=[
                ('articleBlogCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('articleBlogCategoryTwo', models.CharField(max_length=60, null=True)),
                ('ArticleBlogCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleBlogCategory')),
            ],
        ),
    ]
