# Generated by Django 2.0.6 on 2018-07-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180621_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('articleTagId', models.AutoField(primary_key=True, serialize=False)),
                ('articleTagName', models.TextField(null=True)),
                ('articleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-commentId']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='fatherComment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
    ]
