# Generated by Django 2.0.6 on 2018-07-02 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180703_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletag',
            name='articleId',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='fatherComment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
    ]
