# Generated by Django 2.0.6 on 2018-07-03 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180703_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='saveType',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='fatherComment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
    ]
